### ISSUE TITLE
nginx connector v1.0.3 fails to build with GCC 14 / Alpine 3.21 due to implicit declaration of printf in autotest

### ISSUE THREAD

**Issue by breogangf** [owasp-modsecurity/ModSecurity-nginx#373]
## Environment

- ModSecurity-nginx connector: v1.0.3
- ModSecurity library: v3.0.8 (also reproduced with v3.0.14)
- nginx: 1.27.5
- Base image: nginx:1.27.5-alpine3.21 (GCC 14.2.0, Alpine 3.21)

## Description

Building the ModSecurity nginx connector fails during the nginx `./configure`
feature detection phase. The nginx build system generates a small `autotest.c`
probe to detect the ModSecurity connector, which calls `printf("hello")` without
including `<stdio.h>`. Under GCC 14 with `-Werror=format-security` (propagated
by nginx's configure flags), this implicit declaration is treated as a fatal
error.

## Error

```
cc -Os -fstack-clash-protection -Wformat -Werror=format-security -fno-plt -g \
  -I /usr/local/modsecurity/include \
  -o objs/autotest objs/autotest.c \
  -lpcre -Wl,-z,relro \
  -Wl,--copy-dt-needed-entries \
  -Wl,-rpath,/usr/local/modsecurity/lib \
  -L/usr/local/modsecurity/lib -lmodsecurity

objs/autotest.c:7:5: error: implicit declaration of function 'printf'
  [-Wimplicit-function-declaration]
cc1: some warnings being treated as errors
```

## Notes

- The ModSecurity library itself installs correctly (`libmodsecurity.so`, headers).
- The failure is in the connector's `config` feature detection script, which
  triggers nginx's `auto/feature` mechanism to write `autotest.c` without
  `#include <stdio.h>`.
- PR #3342 (merged in v3.0.14) fixes a similar issue for GCC 15 in the library,
  but does **not** cover this connector-side GCC 14 build failure.
- Alpine 3.20 (GCC 13) is unaffected. Alpine 3.21 (GCC 14.2.0) triggers this.

**Comment by airween** [comment]
Hi @breogangf,

thanks for this report.

Please note that the latest version of connector is 1.0.4 which actually [contains](https://github.com/owasp-modsecurity/ModSecurity-nginx/blame/master/config#L14) the fix for this issue. [1.0.4](https://github.com/owasp-modsecurity/ModSecurity-nginx/releases/tag/v1.0.4) was released on 21st of May, 2025, and [1.0.3](https://github.com/owasp-modsecurity/ModSecurity-nginx/releases/tag/v1.0.3)'s release date is 20th of May, 2022 May.

I suggest you to use 1.0.4.

**Comment by breogangf** [comment]
Thanks for the quick response! Confirmed that v1.0.4 resolves this — PR #320 (`fix: Added missing header for conftest`) addresses exactly the issue we hit. Closing this as resolved.
